{% set name = "sqlalchemy-migrate" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0bc02e292a040ade5e35a01d3ea744119e1309cdddb704fdb99bac13236614f8

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pbr
  run:
    - python
    - pbr
    - sqlalchemy
    - decorator
    - six
    - sqlparse
    - tempita

test:
  imports:
    - migrate

about:
  home: https://github.com/openstack/sqlalchemy-migrate
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Database schema migration for SQLAlchemy'

  description: |
    Inspired by Ruby on Rails' migrations, Migrate provides a way to deal with
    database schema changes in SQLAlchemy projects.

    Migrate extends SQLAlchemy to have database changeset handling. It provides
    a database change repository mechanism which can be used from the command
    line as well as from inside python code.
  doc_url: https://sqlalchemy-migrate.readthedocs.io/en/latest/
  dev_url: https://github.com/openstack/sqlalchemy-migrate

extra:
  recipe-maintainers:
    - mxr-conda
    - mariusvniekerk
